#!/bin/sh
####
# tcext - Quick Extension Creation Script for Tiny Core Linux
#
# i wanted to make it easy to create extensions
# so more people will be able to do it
# also i wanted that people will provide inside the extensions
# a tutorial how to make an extension
#
# this script makes your life simpler
# now you have time to describe your work, reread the extention info, and make more extensions
#
# Written by Shimon Doodkin helpmepro1@gmail.com doodkin.com
#
# Contributors:
#  You here - fork and modify https://github.com/shimondoodkin/tcext
#
# lisence: MIT
#

PACK_DIR="$PWD" #execute this file in same  directory where you call ./configure and make
cd $PACK_DIR;


EDITOR="`which vi`";
RESULT="`which nano`"; if [ $? -eq 0 ]; then  EDITOR="$RESULT -w "; fi # if user installed nano maybe he preferrs nano over vi

write_vars_script()
{
### TBD:auto guess more variables, maybe suggest build string from online database
## if you modify this and write $ or `(backquote) backslash them
cat <<ENDOFINFO >$PACK_DIR/tcext.info
##note: this is a shell script
#########  edit package info:  #############

PACK_APP="lighttpd"
APP_VER="1.4.29"
APP_WEBSITE="http://lighttpd.com"

# can copy-paste(SHIFT+INS) a short overview from apps's website:
APP_DESCRIPTION=\`cat <<EOF
Light httpd Web server
EOF
\`

APP_AUTHOR="lighttpd"
APP_COPY="BSD"
PACK_AUTHOR="you"
#write below installation comments
PACK_COMMENTS=\`cat <<EOF
EOF
\`

PACK_ADD_DEPS=\`cat <<EOF
EOF
\`;
#######################################

#write here the build reason: , update date, log date is  MM/DD/YY
PACK_LOG=\`cat <<EOF
`date +%d/%m/%y` Initial Build
EOF
\`;

#each time you build, copy a line from above to here and write above a new date and value
PACK_LOGS=\`cat <<EOF
EOF
\`;

PACK_WHAT_I_DID_IS=\`cat <<EOF
Modify and delete lines here. Also delete This line
example:
simple ./configure and make
example:
i downloaded tar.gz from  www.lighttpd.net/download/
i extraxted it
tcext init  # typed some values
tcext configure --without-bzip2 -with-openssl
tcext make
cp ./doc/config/* to ./tcfiles/etc/lighttpd
prepered my own init script in ./tcfiles/etc/init.d/lighttpd
tcext install
EOF
\`;


ENDOFINFO
#one more thing, create directory for addon files.
if [ -f $PACK_DIR/tcfiles ]; then
  mkdir $PACK_DIR/tcfiles # put in this folder configuration files and other files to copy over the /
fi

}

tcext_flags()
{
export CFLAGS="-march=i486 -mtune=i686 -Os -pipe"
export CXXFLAGS="-march=i486 -mtune=i686 -Os -pipe"
export LDFLAGS="-Wl,-O1"
}

tcext_configure()
{
# TBD: probably better to keep the string saved somewhere
tcext_flags
CONFIGURE_ARGS="`echo \"$@\"|sed \"s/^$1//\"`"  #remove first argument (configure or build)
echo "$CONFIGURE_ARGS" > $PACK_DIR/tcext.configure
echo "`date --rfc-3339=seconds` $CONFIGURE_ARGS" >> $PACK_DIR/tcext.configure-history
./configure $CONFIGURE_ARGS  --prefix=/usr/local
RESULT=$?;
if [ $RESULT -ne 0 ]; then
echo "there was a './configure' error";
echo "there was a './configure' error">> $PACK_DIR/tcext.configure-history;
exit $RESULT;
else
echo "configure ok">> $PACK_DIR/tcext.configure-history;
fi

}

tcext_make()
{
# TBD: probably better to keep the string saved somewhere
tcext_flags
make
RESULT=$?;
if [ $RESULT -ne 0 ]; then
echo "there was a 'make' error">> $PACK_DIR/tcext.configure-history;
exit $RESULT;
else
echo "make ok">> $PACK_DIR/tcext.configure-history;
fi
}

ident_multiline_text()
{
#ident text beutifully, with little work
TEXT=` echo "$1"  | fold -sw 55  ` #  wrap text at 55
TEXT1=`echo "$TEXT" | head -n 1` # no need to ident the first line
TEXT2=`echo "$TEXT" | sed 1d      | sed 's/^.*$/                \0/' ` #ident the other lines
echo "$TEXT1\
$TEXT2" # concat the result
}

tcext_installhalf()
{

#include the package info
. $PACK_DIR/tcext.info

rm /tmp/mark1 >/dev/null
rm /tmp/mark2 >/dev/null
rm /tmp/list >/dev/null
rm -rf /tmp/pkg >/dev/null
mkdir /tmp/pkg

touch /tmp/mark1 #make a time mark in case DESTDIR fails
make install DESTDIR=/tmp/pkg #DESTDIR may not work ... then use:
touch /tmp/mark2 # make end time time mark

#tar is used to copy files by filenames without directories (it creates directories automatically)
if [ "`ls /tmp/pkg/`" == "" ] ; then
find /usr/local -newer /tmp/mark1 -not -newer /tmp/mark2 -not -type d > /tmp/list
tar -T /tmp/list -czvf /tmp/$PACK_APP.tar.gz
cd /tmp/pkg
tar -xf /tmp/$PACK_APP.tar.gz # unpack (install) the extension in tmp
fi

# copy additional files
cp  $PACK_DIR/tcfiles/* /tmp/pkg/ -r

}

tcext_deps()
{
#echo "looking for deps">&2
#cd /tmp/pkg
EXEFILES="`find . | xargs file | grep \"executable\" | grep ELF | cut -f 1 -d : 2> /dev/null; find . | xargs file | grep "shared object" | grep ELF | grep \"not stripped\" | cut -f 1 -d : 2> /dev/null;`"
LIBS="`(
for forfile in $EXEFILES; do
 ldd $forfile|sed -r 's|^\s+(.+)\s+\(0x.+\)$|\1|'|sed -r 's|^(.+)\s+=>\s+(\S+)$|\2|'|sed -r 's|^(.+)\s+=>\s+$|\1|'
done
) | sort | uniq |grep -v 'linux-gate.so.1' |xargs realpath`"

NO_PACKAGE="`echo \"$LIBS\"|awk '!/tcloop/ {print $0}'`"
FOUND_DEPS="`echo \"$LIBS\"|xargs df|sed '/Filesystem/d'|awk '/tcloop/ {print $6}'|sed 's|/tmp/tcloop/||'| sort | uniq | sed 's|^.*$|\0.tcz|'`"
#[ "$NO_PACKAGE" != "" ] && echo -e "No packages found for files:\r\n$NO_PACKAGE">&2
[ "$NO_PACKAGE" != "" ] && echo "$NO_PACKAGE">&2
echo "$FOUND_DEPS"
}

tcext_installfinish()
{
. $PACK_DIR/tcext.info

cd  /tmp/pkg/
find . | xargs file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find . | xargs file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d : | xargs strip -g 2> /dev/null

sudo chmod +x /tmp/pkg/usr/local/tce.installed/$PACK_APP
sudo chown root:staff /tmp/pkg/usr/local/tce.installed/$PACK_APP

PACK_DEPS="`tcext_deps`";

[ ! -e $PACK_DIR/tcout ] && mkdir $PACK_DIR/tcout   # here you receive the result

# make file list for the extension
find | sed 's/^..//' | sed '/^\.$/d' > $PACK_DIR/tcout/$PACK_APP.tcz.list # remove first 2 chars and the dot file

#make loadable file system image file
cd /tmp
mksquashfs pkg/ $PACK_APP.tcz

sudo chown tc:staff /tmp/pkg/usr/local/tce.installed/$PACK_APP

#copy the result to tc out folder

mv $PACK_APP.tcz $PACK_DIR/tcout/
echo "install ok">> $PACK_DIR/tcext.configure-history;

# add md5sum
cd $PACK_DIR/tcout/

md5sum $PACK_APP.tcz > $PACK_APP.tcz.md5.txt

# write dependency file
(
echo "$PACK_ADD_DEPS"
 echo "$PACK_DEPS"
) | sort | uniq | sed -r '/^\s*$/d' >$PACK_DIR/tcout/$PACK_APP.tcz.dep

# TBD: dont know hot to do it yet
# write dependency tree file if required
# dependencies tree idented with spaces
#cat <<EOT >$PACK_DIR/tcout/$PACK_APP.tcz.tree
#EOT
tcext_tree() ##half done TBD
{
tcedone="/tmp/tcedone.$$"
touch ${tcedone}
tcedir="$(cat /opt/.tce_dir)"

depends()
{
   grep -v "^ *$" 2>/dev/null ${tcedir}/optional/$1.tcz.dep |
   while read tce; do
      tce=${tce%.tcz}
      echo "\"${1}\" -> \"${tce}\""
      if ! grep -q "^${tce}.tcz$" ${tcedone}; then
         echo ${tce}.tcz >> ${tcedone}
         depends "${tce}"
      fi
   done
}
cat  ${tcedone}
[ -e  ${tcedone} ] && rm -f ${tcedone}

}

APP_SIZE=`echo \`du -chs $PACK_APP.tcz|grep total |sed s/total//\`` # echo is like trim

APP_DESCRIPTION="`ident_multiline_text \"$APP_DESCRIPTION\"`"
PACK_COMMENTS="`ident_multiline_text \"$PACK_COMMENTS\"`"
PACK_LOG="`ident_multiline_text \"$PACK_LOG\"`"
PACK_LOGS="`ident_multiline_text \"$PACK_LOGS\"`"
PACK_WHAT_I_DID_IS="`ident_multiline_text \"$PACK_WHAT_I_DID_IS\"`"

cat <<EOT >$PACK_DIR/tcout/$PACK_APP.tcz.info
Title:          $PACK_APP
Description:    $APP_DESCRIPTION
Version:        $APP_VER
Author:         $APP_AUTHOR
Original-site:  $APP_WEBSITE
Copying-policy: $APP_COPY
Size:		$APP_SIZE
Extension_by:   $PACK_APP
Comments:       $PACK_COMMENTS

Change-log:     $PACK_LOGS
Current:        $PACK_LOG

Configure:      $PACK_CONFIG
What-I-did-Is:  $PACK_WHAT_I_DID_IS
                -
                Made with tcext https://gist.github.com/1405813

EOT

}

tcext_submit()
{
echo "half done, TBD, to use some simple account from gmail"
##more smtp reference http://www.debian-administration.org/article/Testing_SMTP_servers_with_SWAKS
exit;
{
sleep 5;
echo 'ehlo';
sleep 3;
echo 'MAIL FROM:<freeposter3@gmail.com>';
sleep 3;
echo 'RCPT TO: <kyle@test_dest.com>';
sleep 3;
echo 'DATA';
sleep 3;
echo -e 'To:kyle@testdest.com\nMIME-Version: 1.0 (mime-construct 1.9)\nContent-Type: application/zip\nContent-Transfer-Encoding: base64\n\n';
dd if=/dev/urandom bs=4 count=10 2>/dev/null | openssl base64;
echo '.';
echo '.';
sleep 3;
echo 'quit';
} | nc smtp.gmail.com  25
}

tcext_load()
{
 . $PACK_DIR/tcext.info
 TCE_DIR=`cat /opt/.tce_dir`
 cp -f $PACK_DIR/tcout/$PACK_APP.tcz $TCE_DIR/optional/
 cp -f $PACK_DIR/tcout/$PACK_APP.tcz.md5.txt $TCE_DIR/optional/
 cp -f $PACK_DIR/tcout/$PACK_APP.tcz.dep $TCE_DIR/optional/
 tce-load -i $PACK_APP.tcz
}

tcext_unload()
{
# Copyright 2011 Marco Caminati. Released under GPLv3.
# Pass any content to $keepdir to prevent deleting the directories emptied in the process
set -e
set -u
set -x

# To speed up script, I assumed that: 
# 1) tce-load -i links each /tmp/tcloop/filepath to /filepath
# 2) there is no path in an extension containing " character
# 3) No abmnormously long paths in extension (xargs -n 100 places a very high, but finite, limit on it). Oddly, the increase in execution time got setting -n 1 is unexpectedly low, about +10% (on a very big tcz).

b=busybox
name=`$b echo "$1" | $b sed -e 's_/*$__' | $b egrep -o "[^/]*$"`
mntdir=/tmp/tcloop/$name
keepdir="${keepdir:-}"
mntlist="/proc/mounts"
echo $mntdir | grep -q ! && exit 6
loopdev="$(egrep "${mntdir}" "${mntlist}" | sed "s_\(.*\) squashfs .*\$_\1_" | egrep "${mntdir} *$" | cut -f 1 -d ' ')"
squashfile="$($b losetup | egrep "^ *${loopdev} *:" | cut -f 3- -d " ")"
[ -s "${squashfile}" ] || exit 2
$b umount "${mntdir}" || exit 3
sudo $b mount "${squashfile}" "${mntdir}" -t squashfs -o loop,ro,bs=4096 || exit 4 
# Error 4 is big trouble!
cd "${mntdir}"
find ! -type d | cut -f 2- -d . | sed 's_.*_"&"_'| xargs -r -n 100 $b ls -l | grep -o -- "-> ${mntdir}/.*$"| sed "s_^-> ${mntdir}\(.*$\)_\"\1\"_" | sudo $b xargs -r -n 100 rm
[ "$keepdir" ] || $b find -type d | $b cut -f 2- -d . | $b sed = | $b sed 'N;s/\n/ /' | $b sort -nr | $b cut -f 2- -d " " | $b sed 's/.*/"&"/'| sudo $b xargs -r -n 100 rmdir -p || true
#sort -nr is due to the way rmdir -p works
cd ..
$b umount -d "${mntdir}" || exit 5
cd /usr/local/tce.installed || exit 2
$b find -maxdepth 1 -size +0c | $b egrep -q "${name}" && exit 7
# Debugline for inner consistency check
$b rm "${name}" || true
$b rmdir "${mntdir}"

}


case "${1}" in
init)
. $PACK_DIR/tcext.info
 if [ ! -f $PACK_DIR/tcext.info ]; then
  echo 'tcext.info not found, creating it'
  write_vars_script
  $EDITOR tcext.info
  echo "you can put additional files to copy over / to ./tcfiles "
 else
  echo "tcext.info found, editing..."
  #echo "note: to recreate the file view the file, then  delete it, then run 'tcext init' again"
  $EDITOR tcext.info
 fi
;;
script)
. $PACK_DIR/tcext.info

 if [ ! -f $PACK_DIR/tcfiles/usr/local/tce.installed/$PACK_APP ]; then
  echo "extention init script tcfiles/usr/local/tce.installed/$PACK_APP  not found, creating it"

[ ! -f $PACK_DIR/tcfiles/usr/local/tce.installed ] && mkdir -p $PACK_DIR/tcfiles/usr/local/tce.installed

## backslash ` and $ and \
cat <<EOF >$PACK_DIR/tcfiles/usr/local/tce.installed/$PACK_APP
#!/bin/sh
#
##copy a file not as symlink:
#[ ! -e /etc/lighttpd ] && cp -p /etc/lighttpd.sample /etc/lighttpd
#
##copy directory not as  sym links:
#[ ! -e /etc/lighttpd ] && (mkdir /etc/lighttpd; cd /etc/lighttpd.sample; tar -hpcf - .|tar -xpf - -C /etc/lighttpd)
EOF
  $EDITOR $PACK_DIR/tcfiles/usr/local/tce.installed/$PACK_APP
  chmod +x $PACK_DIR/tcfiles/usr/local/tce.installed/$PACK_APP
 else
  echo "extention init script tcfiles/usr/local/tce.installed/$PACK_APP found, editing..."
  $EDITOR $PACK_DIR/tcfiles/usr/local/tce.installed/$PACK_APP
 fi
;;
flags)
. $PACK_DIR/tcext.info
 tcext_flags
;;
configure)
. $PACK_DIR/tcext.info
 tcext_configure "$@"
;;
make)
. $PACK_DIR/tcext.info
 tcext_make
;;
deps)
 tcext_deps
;;
build)
. $PACK_DIR/tcext.info
 tcext_configure "$@"
 tcext_make
;;
installhalf)
. $PACK_DIR/tcext.info
 if [ ! -f $PACK_DIR/tcext.info ]; then
  $0 init
 else
  $EDITOR tcext.info
 fi
 $0 flags
 echo 'building tcz extension'
 tcext_installhalf
;;
installfinish)
. $PACK_DIR/tcext.info
 tcext_installfinish
;;
install)
. $PACK_DIR/tcext.info
 if [ ! -f $PACK_DIR/tcext.info ]; then
  $0 init
 else
  $EDITOR tcext.info
 fi
 $0 flags
 echo 'building tcz extension'
 tcext_installhalf
 tcext_installfinish
;;
unload)
. $PACK_DIR/tcext.info
tcext_unload "$PACK_APP"
;;
load)
. $PACK_DIR/tcext.info
tcext_load
;;
submit)
. $PACK_DIR/tcext.info
tcext_submit
;;
tools)
TCE_DIR=`cat /opt/.tce_dir`

[ -e $TCE_DIR/optional/compiletc.tcz ] && tce-load -i compiletc.tcz
[ ! -e $TCE_DIR/optional/compiletc.tcz ] && tce-load -w -i compiletc.tcz

[ -e $TCE_DIR/optional/python.tcz ] && tce-load -i python.tcz
[ ! -e $TCE_DIR/optional/python.tcz ] && tce-load -w -i python.tcz

[ -e $TCE_DIR/optional/openssl-1.0.0-dev.tcz ] && tce-load -i openssl-1.0.0-dev.tcz
[ ! -e $TCE_DIR/optional/openssl-1.0.0-dev.tcz ] && tce-load -w -i openssl-1.0.0-dev.tcz

[ -e $TCE_DIR/optional/squashfs-tools-4.x.tcz ] && tce-load -i squashfs-tools-4.x.tcz
[ ! -e $TCE_DIR/optional/squashfs-tools-4.x.tcz ] && tce-load -w -i squashfs-tools-4.x.tcz

[ -e $TCE_DIR/optional/strace.tcz ] tce-load -i strace.tcz
[ ! -e $TCE_DIR/optional/strace.tcz ] tce-load -w -i strace.tcz

[ -e $TCE_DIR/optional/pcre-dev.tcz ] tce-load -i pcre-dev.tcz
[ ! -e $TCE_DIR/optional/pcre-dev.tcz ] tce-load -w -i pcre-dev.tcz

[ -e $TCE_DIR/optional/libtool.tcz ] tce-load -i libtool.tcz
[ ! -e $TCE_DIR/optional/libtool.tcz ] tce-load -w -i libtool.tcz

;;
"--help")
$0 help
;;
help)
cat <<EOF
usage:
tcext all - all tasks are done one after another.
tcext tools - tce-load compiletc and squashfs-tools and other development tools
tcext init - crates tcext.info and shows an editor with the file
tcext script - creates an init script with app's name to rename configuration
tcext configure OPTIONS - does flags, and ./configure \$OPTIONS --prefix=/usr/local
tcext make - does flags and make
tcext install - does make install into a /tmp/pkg folder and puts the file.tcz in ./tcout folder
additional:
tcext flags - a shorthand to exports arch 486 flags... , when you do the ./configure and make manualy
tcext build ARGS- does ./configure \$ARGS && tcext mak
tcext deps - calculate dependencies in current folder
tcext installhalf - does make install into a /tmp/pkg folder and copis tcfiles/* to /tmp/pkg
tcext installfinish - allows split into sub pagages,it packages and puts the file.tcz in ./tcout folder
tcext help - show this message
EOF
;;
all)
 echo "tcext doing all tasks"
. $PACK_DIR/tcext.info
 $0 build
 $0 install
;;
*)# no arguments do all tasks
$0 help
;;
esac
